const sortFanwork = (works, key = "title") =>
  works.sort((left, right) =>
    (left.author.replace(/^(@)/, "") + left[key]).localeCompare(
      right.author.replace(/^(@)/, "") + right[key]
    )
  );

const fics = sortFanwork([
  // -- ADD YOUR FICS HERE --
  {
    url: "https://archiveofourown.org/works/27287347",
    title: "Rebooting",
    words: 293,
    author: "ENBY",
    characters: ["Emmett Internet"],
  },
  {
    url:
      "https://docs.google.com/document/d/18Vg6VQuudZoPE7BFbi4_1LLj57wzXw3t7hd8S8lwtjM/edit?usp=sharing",
    title: "This Is Me",
    words: 922,
    author: "slavfox",
    characters: ["Nagomi Nava"],
  },
  {
    url:
      "https://docs.google.com/document/d/1yrhbP46F67OgNgwRzg0xSAikOE3dEi8qZIPVZssUzr8/edit?usp=sharing",
    title: "Haunted Moon Island",
    words: 1014,
    author: "Solistic Barb",
    characters: ["Other/multiple"],
  },
  {
    url:
      "https://docs.google.com/document/d/1AuM4HeM6MLypvpE0iWs5loQQHTxqLwBL0ZcBoYYOtpE/edit?usp=sharing",
    title: "Precognition",
    words: 924,
    author: "dasy",
    characters: ["Nagomi Nava"],
  },
  {
    url: "https://archiveofourown.org/works/27181150/chapters/66388855",
    title: "The Last Hell Series",
    words: 1702,
    author: "Emily | RireMakar",
    characters: ["Nagomi Nava"],
  },
  {
    url: "https://archiveofourown.org/works/26404318",
    title: "Looking Back",
    words: 1892,
    author: "Emily | RireMakar",
    characters: ["Emmett Internet", "Randall Marijuana"],
  },
  {
    url: "https://archiveofourown.org/works/27205444",
    title: "sunbeams rainy day chillin",
    words: 1011,
    author: "starboy",
    characters: ["Other/multiple"],
  },
  // -- END FICS --
]);

const music = sortFanwork([
  // -- ADD YOUR MUSIC HERE --
  {
    url: "https://thegarages.bandcamp.com/track/the-tug",
    title: "The Tug",
    author: "amadis",
  },
  {
    url: "https://thegarages.bandcamp.com/track/do-not-come-to-the-hellmouth",
    title: "Don't Come To The Hellmouth",
    author: "slavfox",
  },
  {
    url: "https://www.youtube.com/watch?v=Cihbcuii9WA",
    title: "bury our light",
    author: "slavfox",
  },
]);

var shuffle = (array) => {
  var currentIndex = array.length;
  var temporaryValue, randomIndex;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {
    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
};

const art = sortFanwork(
  [
    // -- ADD YOUR ART HERE --
    {
      url: "https://twitter.com/CKaelde/status/1320040538704314368/photo",
      src: "/fanart/CKaelde_Nagomi.png",
      author: "@CKaelde",
      author_link: "https://twitter.com/CKaelde",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1316763493916438531",
      src: "/fanart/slavfoxman_iwillnotallowit.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1314282058106245120/photo/1",
      src: "/fanart/slavfoxman_gomester_wanted_poster.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1311725025066704896/photo/1",
      src: "/fanart/slavfoxman_bickle_pitching.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Eugenia Bickle"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1311949280811327488/photo/1",
      src: "/fanart/slavfoxman_monsieur_beam_moose.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Monsieur Beam"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1302032563393957889/photo/1",
      src: "/fanart/slavfoxman_sutton_tlopps_card.png",
      author: "@slavfoxman",
      characters: ["Sutton Bishop"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1301946037704196097/photo/1",
      src: "/fanart/slavfoxman_sutton_shopping.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Sutton Bishop"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1301582950870417415/photo/1",
      src: "/fanart/slavfoxman_nagomi_tlopps.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1322929459645788161",
      src: "/fanart/slavfoxman_ferryman_nagomi.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1299731960730923011/photo/1",
      src: "/fanart/slavfoxman_nagomi_walking.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1306958708149280774/photo/1",
      src: "/fanart/slavfoxman_aro_nagomi_comic.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/slavfoxman/status/1310277601257193477/photo/1",
      src: "/fanart/slavfoxman_tentacle_horror_nagomi.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Nagomi Nava"],
      blur: true,
      cw: "cw: tentacle horror Nagomi",
    },
    {
      url: "https://twitter.com/slavfoxman/status/1320809885819412487/photo/1",
      src: "/fanart/slavfoxman_nagomi_adaptation.png",
      author: "@slavfoxman",
      author_link: "https://twitter.com/slavfoxman",
      characters: ["Nagomi Nava", "Hahn Fox"],
      blur: false,
    },
    {
      url: "/fanart/hillexed_homeless_moonba_full.png",
      src: "/fanart/hillexed_homeless_moonba.png",
      author: "@hillexed",
      author_link: "https://twitter.com/hillexed",
      characters: ["Moonba"],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1316454078902398980/photo/1",
      src: "/fanart/larkiiiine_gomi.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1321431144429215744/photo/1",
      src: "/fanart/larkiiiine_cat_cafe.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: ["Nagomi Nava", "Hahn Fox"],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1317522798093438976/photo/1",
      src: "/fanart/larkiiiine_party.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: [
        "Nagomi Nava",
        "Sutton Bishop",
        "Zack Sanders",
        "Sandoval Crossing",
        "Eugenia Bickle",
        "Lars Taylor",
        "Dudley Mueller",
      ],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1318601762186690562/photo/1",
      src: "/fanart/larkiiiine_friends.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: ["Randall Marijuana", "Emmett Internet"],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1318604833469943811/photo/1",
      src: "/fanart/larkiiiine_friends2.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: ["Randall Marijuana", "Emmett Internet", "Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1320380827910418432/photo/1",
      src: "/fanart/larkiiiine_celebration.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: [
        "Nerd Pacheco",
        "Lars Taylor",
        "Igneus Delacruz",
        "Nagomi Nava",
        "Sutton Bishop",
        "Miguel James",
        "Hahn Fox",
      ],
      blur: false,
    },
    {
      url: "https://twitter.com/larkiiiine/status/1319311820113543171/photo/1",
      src: "/fanart/larkiiiine_magmatic.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "/fanart/larkiiiine_duds_full.png",
      src: "/fanart/larkiiiine_duds.png",
      author: "@larkiiiine",
      author_link: "https://twitter.com/larkiiiine/",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "/fanart/ivi_pessoa_tigerbeams_full.png",
      src: "/fanart/ivi_pessoa_tigerbeams.png",
      author: "@Ivi_Pessoa",
      author_link: "https://twitter.com/Ivi_Pessoa",
      characters: ["Other"],
      blur: false,
    },
    {
      url: "/fanart/pichi_emmett_full.png",
      src: "/fanart/pichi_emmett.png",
      author: "Pichi2214",
      author_link: null,
      characters: ["Emmett Internet"],
      blur: false,
    },
    // Coblin
    {
      url: "/fanart/krasi_savov_bickle_full.png",
      src: "/fanart/krasi_savov_bickle.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Eugenia Bickle"],
      blur: false,
    },
    {
      url: "https://twitter.com/Krasi_Savov/status/1317756008903659520/photo/1",
      src: "/fanart/krasi_savov_duds.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_emmet2a_full.png",
      src: "/fanart/krasi_savov_emmet2a.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Emmett Internet"],
      blur: false,
    },
    {
      url: "https://twitter.com/Krasi_Savov/status/1316468128923242504/photo/1",
      src: "/fanart/krasi_savov_hahn.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Hahn Fox"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_hendricks_full.png",
      src: "/fanart/krasi_savov_hendricks.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Hendricks Richardson"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_iggy_full.png",
      src: "/fanart/krasi_savov_iggy.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Igneus Delacruz"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_jeff2_full.png",
      src: "/fanart/krasi_savov_jeff2.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["JEFF!"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_lars_full.png",
      src: "/fanart/krasi_savov_lars.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_miguel_full.png",
      src: "/fanart/krasi_savov_miguel.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Miguel James"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_moonroomba_full.png",
      src: "/fanart/krasi_savov_moonroomba.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Moonba"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_nagomi_full_1.png",
      src: "/fanart/krasi_savov_nagomi_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_nerd_full_1.png",
      src: "/fanart/krasi_savov_nerd_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Nerd Pacheco"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_randy1_full_1.png",
      src: "/fanart/krasi_savov_randy1_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/Krasi_Savov/status/1318195220362764288/photo/1",
      src: "/fanart/krasi_savov_sandy_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Sandoval Crossing"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_sigmund_full_1.png",
      src: "/fanart/krasi_savov_sigmund_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Sigmund Castillo"],
      blur: false,
    },
    {
      url: "https://twitter.com/Krasi_Savov/status/1318195220362764288/photo/1",
      src: "/fanart/krasi_savov_sutton2_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Sutton Bishop"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_sutton_full_1.png",
      src: "/fanart/krasi_savov_sutton_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Sutton Bishop"],
      blur: false,
    },
    {
      url: "/fanart/krasi_savov_zack_full_1.png",
      src: "/fanart/krasi_savov_zack_1.png",
      author: "@Krasi_Savov",
      author_link: "https://twitter.com/Krasi_Savov",
      characters: ["Zack Sanders"],
      blur: false,
    },
    // Glempy
    {
      url: "https://twitter.com/Glempy/status/1301863622193426433/photo/1",
      src: "/fanart/glempy_emmett.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Emmett Internet"],
      blur: false,
    },
    {
      url: "https://twitter.com/Glempy/status/1306666083387150337/photo/1",
      src: "/fanart/glempy_hahn.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Hahn Fox"],
      blur: false,
    },
    {
      url: "https://twitter.com/Glempy/status/1300504809250881536/photo/1",
      src: "/fanart/glempy_hollywoof.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "https://twitter.com/Glempy/status/1292096715210870785/photo/1",
      src: "/fanart/glempy_hollywood.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "https://twitter.com/Glempy/status/1298238334800625664/photo/1",
      src: "/fanart/glempy_malik.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Malik Romayne"],
      blur: false,
    },
    {
      url: "/fanart/glempy_sutton_full.jpg",
      src: "/fanart/glempy_sutton.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Sutton Bishop"],
      blur: false,
    },
    {
      url: "/fanart/glempy_hendricks_full.jpg",
      src: "/fanart/glempy_hendricks.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Hendricks Richardson"],
      blur: false,
    },
    {
      url: "/fanart/glempy_hendricks2_full.jpg",
      src: "/fanart/glempy_hendricks2.jpg",
      author: "@Glempy",
      author_link: "https://twitter.com/Glempy/",
      characters: ["Hendricks Richardson"],
      blur: false,
    },
    // Copper / Laurel
    {
      url: "/fanart/copper_laurel_emmett_full.png",
      src: "/fanart/copper_laurel_emmett.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Emmett Internet"],
      blur: false,
    },
    {
      url: "/fanart/copper_laurel_iggynus_full.png",
      src: "/fanart/copper_laurel_iggynus.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Igneus Delacruz"],
      blur: false,
    },
    {
      url: "/fanart/copper_laurel_ignition_full.png",
      src: "/fanart/copper_laurel_ignition.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Igneus Delacruz", "Randall Marijuana"],
      blur: false,
    },
    {
      url: "/fanart/copper_laurel_lars2_full.png",
      src: "/fanart/copper_laurel_lars2.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "/fanart/copper_laurel_lars_full.png",
      src: "/fanart/copper_laurel_lars_full.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "/fanart/copper_laurel_layna_full.png",
      src: "/fanart/copper_laurel_layna.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "/fanart/copper_laurel_power_couple_full.png",
      src: "/fanart/copper_laurel_power_couple.png",
      author: "Copper / Laurel",
      author_link: "https://twitter.com/camerupts/",
      characters: ["Malik Romayne", "Igneus Delacruz"],
      blur: false,
    },
    // pysics
    {
      url: "https://twitter.com/_pysics/status/1315793256953806849/photo/1",
      src: "/fanart/pysics_alaynabella.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "/fanart/pysics_casual_nagomi_full.jpg",
      src: "/fanart/pysics_casual_nagomi.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "/fanart/pysics_cowboy_hollywood_full.jpg",
      src: "/fanart/pysics_cowboy_hollywood.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "/fanart/pysics_hahn_full.jpg",
      src: "/fanart/pysics_hahn.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Hahn Fox"],
      blur: false,
    },
    {
      url: "https://twitter.com/_pysics/status/1309694286808707072/photo/2",
      src: "/fanart/pysics_hollyweed.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "https://twitter.com/_pysics/status/1309694286808707072/photo/1",
      src: "/fanart/pysics_lars.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "/fanart/pysics_layna_full.png",
      src: "/fanart/pysics_layna.png",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "https://twitter.com/_pysics/status/1310576592477970432/photo/2",
      src: "/fanart/pysics_nagomi.png",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/_pysics/status/1310576592477970432/photo/1",
      src: "/fanart/pysics_nagomi_dinger.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "/fanart/pysics_randall_feedback_full.jpg",
      src: "/fanart/pysics_randall_feedback.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Randall Marijuana"],
      blur: false,
    },
    {
      url: "/fanart/pysics_randall_inci_full.jpg",
      src: "/fanart/pysics_randall_inci.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/_pysics/status/1317527008671354881/photo/1",
      src: "/fanart/pysics_weedbros.png",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/_pysics/status/1312413608526127107/photo/1",
      src: "/fanart/pysics_zack.jpg",
      author: "pysics",
      author_link: "https://twitter.com/_pysics/",
      characters: ["Zack Sanders"],
      blur: false,
    },
    // Mako
    {
      url: "https://twitter.com/justmako/status/1301671383986995200/photo/1",
      src: "/fanart/mako_alt_iggy.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Igneus Delacruz"],
      blur: false,
    },
    {
      url: "/fanart/mako_blood_emmett_full.png",
      src: "/fanart/mako_blood_emmett.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Emmett Internet", "Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1308107530007175169/photo/1",
      src: "/fanart/mako_dudley_mueller.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1320548521112702976/photo/1",
      src: "/fanart/mako_duds_iconhood.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1317254971436433408/photo/1",
      src: "/fanart/mako_duds_partying.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1315824726254776320/photo/1",
      src: "/fanart/mako_duds_slurp.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1299510063204380672/photo/1",
      src: "/fanart/mako_emmett_internet.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Emmett Internet"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1306994673567903744/photo/1",
      src: "/fanart/mako_emmett_ren.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Emmett Internet", "Other"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1309192012583915520/photo/1",
      src: "/fanart/mako_flames_of_james.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Miguel James"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1303149035273023488/photo/1",
      src: "/fanart/mako_mall_hangs.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Nagomi Nava", "Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1305006161545121792/photo/1",
      src: "/fanart/mako_monsieur_bean.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Monsieur Beam"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1300870609870770185/photo/1",
      src: "/fanart/mako_seven_helleven.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Randall Marijuana"],
      blur: false,
    },
    {
      url: "/fanart/mako_siggy_full.png",
      src: "/fanart/mako_siggy.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Sigmund Castillo"],
      blur: false,
    },
    {
      url: "https://twitter.com/justmako/status/1299510298160902144/photo/1",
      src: "/fanart/mako_zack.png",
      author: "@justmako",
      author_link: "https://twitter.com/justmako/",
      characters: ["Zack Sanders"],
      blur: false,
    },
    // Karagna
    {
      url: "/fanart/karagna_coach_sol_full.png",
      src: "/fanart/karagna_coach_sol.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Coach Sol"],
      blur: false,
    },
    {
      url: "/fanart/karagna_duds_full.png",
      src: "/fanart/karagna_duds.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "/fanart/karagna_horne_full.png",
      src: "/fanart/karagna_horne.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Alexander Horne"],
      blur: false,
    },
    {
      url: "/fanart/karagna_horne_2_full.png",
      src: "/fanart/karagna_horne_2.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Alexander Horne"],
      blur: false,
    },
    {
      url: "/fanart/karagna_iggy1_full.png",
      src: "/fanart/karagna_iggy1.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Igneus Delacruz"],
      blur: false,
    },
    {
      url: "/fanart/karagna_igneus_full.png",
      src: "/fanart/karagna_igneus.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Igneus Delacruz"],
      blur: false,
    },
    {
      url: "/fanart/karagna_lars_full.png",
      src: "/fanart/karagna_lars.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "/fanart/karagna_nerd_full.png",
      src: "/fanart/karagna_nerd.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Nerd Pacheco"],
      blur: false,
    },
    {
      url: "/fanart/karagna_prom_nerd_full.png",
      src: "/fanart/karagna_prom_nerd.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Nerd Pacheco"],
      blur: false,
    },
    {
      url: "/fanart/karagna_sun_swallowed_full.png",
      src: "/fanart/karagna_sun_swallowed.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Hahn Fox", "Coach Sol", "Nerd Pacheco"],
      blur: false,
    },
    {
      url: "/fanart/karagna_visit_hellmouth_full.png",
      src: "/fanart/karagna_visit_hellmouth.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: [],
      blur: false,
    },
    {
      url: "/fanart/karagna_zack_full.png",
      src: "/fanart/karagna_zack.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Zack Sanders"],
      blur: false,
    },
    {
      url: "/fanart/karagna_zack_hlomecoming_full.png",
      src: "/fanart/karagna_zack_hlomecoming.png",
      author: "@Karagna_",
      author_link: "https://twitter.com/Karagna_",
      characters: ["Zack Sanders"],
      blur: false,
    },
    // mandy
    {
      url: "https://twitter.com/alienmandy_/status/1307298627631476737/photo/1",
      src: "/fanart/alienmandy_beamsstickers.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: [
        "Hahn Fox",
        "Nagomi Nava",
        "Lars Taylor",
        "Sutton Bishop",
        "Sandoval Crossing",
        "Igneus Delacruz",
        "Miguel James",
        "Nerd Pacheco",
        "Eugenia Bickle",
        "Dudley Mueller",
        "Malik Romayne",
        "Zack Sanders",
        "Sigmund Castillo",
        "Hendricks Richardson",
      ],
      blur: false,
    },
    {
      url: "https://twitter.com/alienmandy_/status/1321277419777449985/photo/1",
      src: "/fanart/alienmandy_duds.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "https://twitter.com/alienmandy_/status/1317712919119867904/photo/1",
      src: "/fanart/alienmandy_emrandallbeams.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: ["Emmett Internet", "Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/alienmandy_/status/1317712919119867904/photo/2",
      src: "/fanart/alienmandy_emrandallsquid.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: ["Emmett Internet", "Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/alienmandy_/status/1299682611975999491/photo/2",
      src: "/fanart/alienmandy_gomi.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: ["Nagomi Nava"],
      blur: false,
    },
    {
      url: "https://twitter.com/alienmandy_/status/1299682611975999491/photo/1",
      src: "/fanart/alienmandy_randy.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: ["Randall Marijuana"],
      blur: false,
    },
    {
      url: "https://twitter.com/alienmandy_/status/1321353843767037959/photo/1",
      src: "/fanart/alienmandy_manyrays_onesun.jpg",
      author: "@alienmandy_",
      author_link: "https://alienmandy.com/",
      characters: ["Other"],
      blur: false,
    },
    // Mimimi
    {
      url: "https://twitter.com/MimimiCee/status/1320205020076408833",
      src: "/fanart/mimimicee_champions.webp",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Other"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1291381794152099842/photo/1",
      src: "/fanart/mimimicee_into_the_sun.png",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Other"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1320108896095248387/photo/1",
      src: "/fanart/mimimicee_day_115_lars.png",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1310238742175715328/photo/1",
      src: "/fanart/mimimicee_hlomecoming_lars.jpg",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1310238742175715328/photo/2",
      src: "/fanart/mimimicee_hlomecoming_lars_2.jpg",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1304449999934238723",
      src: "/fanart/mimimicee_lars.webp",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1317127618324553730/photo/1",
      src: "/fanart/mimimicee_lars_growing_up.jpg",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1308815478870224897/photo/1",
      src: "/fanart/mimimicee_lars_layna.jpg",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor", "Alaynabella Hollywood"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1318304832101515266/photo/1",
      src: "/fanart/mimimicee_new_star_lars.png",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Lars Taylor"],
      blur: false,
    },
    {
      url: "https://twitter.com/MimimiCee/status/1305923634570113025/photo/1",
      src: "/fanart/mimimicee_randy_ted.jpg",
      author: "@MimimiCee",
      author_link: "https://twitter.com/MimimiCee",
      characters: ["Randall Marijuana", "Other"],
      blur: false,
    },
    // King Mudkip
    {
      url: "https://twitter.com/King_Mudkip/status/1323478716266274816/photo/1",
      src: "/fanart/kingmudkip_duds.webp",
      author: "@King_Mudkip",
      author_link: "https://twitter.com/King_Mudkip",
      characters: ["Dudley Mueller"],
      blur: false,
    },
    {
      url: "https://twitter.com/King_Mudkip/status/1329580751478681603",
      src: "/fanart/kingmudkip_lars.webp",
      author: "@King_Mudkip",
      author_link: "https://twitter.com/King_Mudkip",
      characters: ["Lars Taylor"],
      blur: false,
    },
  ],
  "src"
).map((work, index) => ({ id: index, ...work }));
